version: "3"

services:
  quantanalyst_django:
    build:
      context: ./
      dockerfile: ./quantanalyst/django.development.Dockerfile
    volumes:
      - ./quantanalyst/:/quantanalyst/
      - ./apps/:/apps/
    networks:
      quantanalyst_network:
        ipv4_address: 172.16.99.11

  quantanalyst_nginx:
    build:
      context: ./
      dockerfile: ./nginx/nginx.development.Dockerfile
    networks:
      quantanalyst_network:
        ipv4_address: 172.16.99.10

networks:
  quantanalyst_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.99.0/24
