version: "3"

services:

  quantanalyst_django:
    build:
      context: ./
      dockerfile: ./django/development.Dockerfile
    volumes:
      - ./django/quantanalyst/:/quantanalyst/
      - ./django/apps/:/apps/
      - ./django/templates/:/templates/
      - ./django/modules/:/modules/
    env_file:
      - ./.env.quantanalyst_django
    command: gunicorn quantanalyst.wsgi:application -b 0.0.0.0:8000
    networks:
      quantanalyst_network:
        ipv4_address: 172.16.99.11
    depends_on:
      - quantanalyst_postgres


  quantanalyst_postgres:
    image: postgres:11.3-alpine
    env_file:
      - ./.env.quantanalyst_postgres
    volumes:
      - ../quantanalyst_database/:/var/lib/postgresql/data/
    networks:
      quantanalyst_network:
        ipv4_address: 172.16.99.12


  quantanalyst_nginx:
    image: nginx:1.15.12-alpine
    volumes:
      - ./nginx/developmenent.conf.d/:/etc/nginx/conf.d/
      - ./staticfiles/:/staticfiles/
    networks:
      quantanalyst_network:
        ipv4_address: 172.16.99.10
    depends_on:
      - quantanalyst_django


networks:
  quantanalyst_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.99.0/24
