# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpython', '0005_testblogentry_wert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testblogentry',
            name='datum',
            field=models.DateField(blank=True),
        ),
    ]
