version: "3"

services:
  quantanalyst_django:
    build:
      context: ../quantanalyst
      dockerfile: dockerfile-django-production

  quantanalyst_nginx:
    networks:
      quantanalyst_network:
        ipv4_address: 172.16.99.10

networks:
  quantanalyst_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.99.0/24

