# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181212_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemenuitems',
            name='active',
            field=models.BooleanField(verbose_name='active'),
        ),
    ]
