# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpython', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstEntry',
        ),
    ]
