# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 23:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpython', '0007_testblogentry_titel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testblogentry',
            name='titel',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
