# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpython', '0008_auto_20181125_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testblogentry',
            name='wert',
        ),
        migrations.AddField(
            model_name='testblogentry',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
