FROM python:3.5-alpine

WORKDIR /quantanalyst

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
	&& apk add --virtual build-deps gcc python3-dev musl-dev \
	&& apk add postgresql-dev \
	&& pip install psycopg2

COPY requierments-development.txt .
RUN pip install -r requierments-development.txt
RUN apk del build-deps
