FROM python:3.6-alpine

ENV PYTHONDONTWRITEBYTECODE 1 
ENV PYTHONBUFFERED 1 

RUN pip install --upgrade pip
RUN apk update \
	&& apk add --virtual build-deps gcc python3-dev musl-dev \
	&& apk add postgresql-dev \
	&& pip install psycopg2 \
	&& apk del build-deps
