# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-13 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181212_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemenuitems',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
